# fly.toml app configuration file generated for charts-server on 2024-01-25T09:39:54+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apy-server"
primary_region = "ams"

[env]


[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[http_service.concurrency]
hard_limit = 10000
soft_limit = 7500
type = "connections"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 512

[[http_service.checks]]
grace_period = "10s"
interval = "30s"
method = "GET"
timeout = "5s"
path = "/api/health"

