FROM node:22 as dev

ENV YARN_CACHE_FOLDER=/root/.yarn

WORKDIR /app

RUN npm install -g corepack@latest && corepack enable && corepack prepare yarn@4.9.2 --activate

COPY . .

RUN --mount=type=cache,id=yarn,target=/root/.yarn \
 yarn install --immutable \
 && yarn docker

# Production npm modules



# Final image

FROM gcr.io/distroless/nodejs22-debian12 as app

EXPOSE 8000
WORKDIR /app
COPY --from=dev /app /app
CMD ["--enable-source-maps", "/app/build/main.js"]
